version: '3.8'

services:
  ui:
    build: ..
    ports:
      - "8000:8000"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://localhost:11434

  backend:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
